# Generated by Django 4.2 on 2024-02-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='descripition',
            new_name='description',
        ),
    ]
